---

- name: keys - create key destination
  file:
    state=directory
    path=~/.ssh/provision
    mode=0755

- name: keys - copy keys
  copy:
    src={{ item }}
    dest=~/.ssh/provision/
    mode=600
  with_items: provision_keys

